# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3bf74fe9b64db93ce90535e06a975a11d21e5643c79901394962bb191a2f31c8be6630552997a642847e4e928cdbd7942d1ac908191dd29f86e1588b17ea26a

test:
  secret_key_base: 47a8863bca7d3353e64d0d63eed0f9ad1d9fbe18d57791234ee7e1c4c196d68105f985111613dd722c4b9321358712f18a32225c440454198f7a734dfaed5e5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
